### PR TITLE
Fix trivy analysis reported issues

### PR DESCRIPTION
**Pull request by Prajyot-Parab**
**What this PR does / why we need it**:
- Fix trivy analysis reported issues
  - bump golang to v1.21.8
  - bump oras-go to v1.2.5

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

/area provider/ibmcloud

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Release note**:

```release-note
Fix trivy analysis reported issues
```

### CODE REVIEW

**Review by Amulyam24 — APPROVED** [review]
/lgtm

**Comment by Amulyam24** [comment]
@Prajyot-Parab, can we update github.com/aquasecurity/trivy from 0.48.3 to 0.50.1 as a part of this PR and check?

**Comment by Prajyot-Parab** [comment]
> @Prajyot-Parab, can we update github.com/aquasecurity/trivy from 0.48.3 to 0.50.1 as a part of this PR and check?

@Amulyam24 that wont work for now.

It is dependent on this PR of mine - https://github.com/aquasecurity/trivy/pull/6387

**Pull request merged**
