### PR TITLE
remove uselsess id annotation, we have it in PROVIDERID

### PR DESCRIPTION
**Pull request by xunpan**
clean duplicated information

### CODE REVIEW

**Comment by jichenjc** [comment]
make sense, we should use provider ID ,however, will it be helpful to some other functions to use the annotation such as cloud provider? do know have the knowledge defined in the cluster-api CRD?

**Comment by xunpan** [comment]
`providerID` is maintained in `cluster-api` `Machine` definition.

**Comment by jichenjc** [comment]
I knew it's maintained in cluster-api, will the CRD of machine defined in cluster-api or other cloud relaetd project know / has capability to access the provider ID info, right?

**Comment by xunpan** [comment]
No matter `annotation` or `providerID`, they are part of `Machine` data. They share same RBAC. If you can query it, you can get informaiton from both. It has no different I think.

**Comment by jichenjc** [comment]
ok, thanks for the info , really appreciate , I might have wrong thought here..

/lgtm

**Pull request merged**
