### PR TITLE
Update cluster-api to v1.2.5

### LINKED ISSUE #951: Update capi to 1.2.5
/kind cleanup
/area provider/ibmcloud

**What steps did you take and what happened:**
Lets use capi version to 1.2.5 in both main and release-0.3 branches

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version:
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by Prajyot-Parab**
Signed-off-by: Prajyot-Parab <prajyot.parab2@ibm.com>

**What this PR does / why we need it**:
- Update cluster-api to v1.2.5

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #951 

**Special notes for your reviewer**:

/area provider/ibmcloud

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Release note**:

```release-note
Update cluster-api to v1.2.5
```

### CODE REVIEW

**Comment by Amulyam24** [comment]
@Prajyot-Parab, the `hack/tools/go.mod` should also be updated

**Comment by Prajyot-Parab** [comment]
> @Prajyot-Parab, the `hack/tools/go.mod` should also be updated

Done. Thanks for pointing out.

**Review by Amulyam24 — APPROVED** [review]
/lgtm

**Review by mkumatag — APPROVED** [review]
/lgtm

**Comment by mkumatag** [comment]
@Prajyot-Parab lets cherrypick this to release-0.3 branch as well.

**Comment by Prajyot-Parab** [comment]
will do manual cherry-pick

**Pull request merged**
