### PR TITLE
handle image import job properly

### PR DESCRIPTION
**Pull request by mkumatag**
**What this PR does / why we need it**:

Added a new condition to log the image import state properly and also include the state for the image from the import job.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

/area provider/ibmcloud

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by mkumatag** [comment]
need a must review from @Prajyot-Parab 

/hold

**Comment by Prajyot-Parab** [comment]
/lgtm


Thanks! @mkumatag

**Comment by mkumatag** [comment]
removing hold now 

/unhold

**Pull request merged**
