### PR TITLE
Updated registry to quay.io/cluster-api-provider-ibmcloud.

### PR DESCRIPTION
**Pull request by gyliu513**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/issues/113

**Special notes for your reviewer**:

/sig ibmcloud

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Release note**:

```release-note
NONE
```

/cc @xunpan @jichenjc @hchenxa

### CODE REVIEW

**Comment by gyliu513** [comment]
I have just pushed a v0.1 image.

```
root@gyliu-c11:~# docker pull quay.io/cluster-api-provider-ibmcloud/ibmcloud-cluster-api-controller:v0.1.0
v0.1.0: Pulling from cluster-api-provider-ibmcloud/ibmcloud-cluster-api-controller
898c46f3b1a1: Pull complete
63366dfa0a50: Pull complete
041d4cd74a92: Pull complete
6e1bee0f8701: Pull complete
d93a12e527a9: Pull complete
087420fbbfa3: Pull complete
Digest: sha256:a920d9ccc5ef600a30911073d491cdc8c500ce6c9a24880d3f0c72a0b9e61af1
Status: Downloaded newer image for quay.io/cluster-api-provider-ibmcloud/ibmcloud-cluster-api-controller:v0.1.0
```

**Comment by hchenxa** [comment]
miss the file https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/blob/master/config/manager/manager.yaml#L58

**Comment by gyliu513** [comment]
@hchenxa done.

**Comment by hchenxa** [comment]
LGTM

**Pull request merged**
