### PR TITLE
Fix docker buildx build

### LINKED ISSUE #629: post-ibm-powervs-cloud-provider-push-images job failed
/kind bug
/area provider/ibmcloud

**What steps did you take and what happened:**
https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/post-ibm-powervs-cloud-provider-push-images/1513791885783601152

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version:
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by Karthik-K-N**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #629

**Special notes for your reviewer**:

/area provider/ibmcloud

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by mkumatag — APPROVED** [review]
/lgtm
/approve

**Comment by mkumatag** [comment]
@Karthik-K-N image pushed: `gcr.io/k8s-staging-capi-ibmcloud/powervs-cloud-controller-manager:9b99b4e_a6bfa07`

**Comment by Karthik-K-N** [comment]
> gcr.io/k8s-staging-capi-ibmcloud/powervs-cloud-controller-manager:9b99b4e_a6bfa07

Nice, I think i can update the image in [deployment](https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/blob/3fdb551186c3ed90127300403ea11aaaabfc299b/templates/cluster-template-powervs-cloud-provider.yaml#L469) now. But will the image name conflict?

**Comment by mkumatag** [comment]
> > gcr.io/k8s-staging-capi-ibmcloud/powervs-cloud-controller-manager:9b99b4e_a6bfa07
> 
> Nice, I think i can update the image in [deployment](https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/blob/3fdb551186c3ed90127300403ea11aaaabfc299b/templates/cluster-template-powervs-cloud-provider.yaml#L469) now. But will the image name conflict?

conflict with what?

**Comment by Karthik-K-N** [comment]
I was just thinking , will the newly built images in future  conflict with the existing, Since we use same image tag.

**Comment by mkumatag** [comment]
> I was just thinking , will the newly built images in future  conflict with the existing, Since we use same image tag.

When we change the sha, image will have a different tag. If we rebuild the same image with same tag then it will just overwrite the existing image. I don't see issue in both the cases.

**Pull request merged**
