### PR TITLE
Add custom type for resource not found error

### PR DESCRIPTION
**Pull request by Amulyam24**
**What this PR does / why we need it**:
Add custom type for resource not found error

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

/area provider/ibmcloud

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Release note**:

```release-note
Add custom type for resource not found error
```

### CODE REVIEW

**Review by Prajyot-Parab — APPROVED** [review]
/lgtm

**Review by Karthik-K-N — COMMENTED** [review]
I agree for defining these messages globally, But do we need to define them within api's, Usually api's are not only used within the repo, its meant to be imported by clients. So does these make any use for external consumption apart from using it internal? If not then we can define them within in file in scope or somewhere.

I defer the decision to you.

**Comment by Amulyam24** [comment]
> I agree for defining these messages globally, But do we need to define them within api's, Usually api's are not only used within the repo, its meant to be imported by clients. So does these make any use for external consumption apart from using it internal? If not then we can define them within in file in scope or somewhere.
> 
> I defer the decision to you.

@Karthik-K-N, I agree on defining it within the package scope as it will not be used beyond it. Changes applied, PTAL!

**Review by Karthik-K-N — COMMENTED** [review]
Thank you.

/lgtm

**Review by Karthik-K-N — COMMENTED** [review]
/hold cancel

**Pull request merged**
