### PR TITLE
[WIP]fix image vulnerabilities issue.

### PR DESCRIPTION
**Pull request by morvencao**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/issues/115

**Special notes for your reviewer**:

/sig ibmcloud

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by gyliu513** [comment]
@morvencao seems the prow works now, great!! We need to add more to prow, like unit test, push image etc. 

FYI @xunpan

**Comment by xunpan** [comment]
@morvencao 
Does current fix work? If yes, please remove `WIP`.

**Comment by morvencao** [comment]
@xunpan I don't think so, even if we switch new base image, it still has some vulnerabilities issues. 
Looks like this is a common issue for many provider implementation.

 I was thinking why not build the binary with `static` lib and use `scratch` as base image, but we need the ca-certificates package. 

Any insight for this?

**Comment by xunpan** [comment]
Please try to use `FROM alpine:latest` as your base image. 

It is small, simple and security Linux distribution and is used by several images with vulnerabilities detection free in quay.

**Comment by morvencao** [comment]
@wanghh2000 PTAL

**Comment by morvencao** [comment]
Closing this in favor of https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/pull/204

**Pull request closed without merging**
