### PR TITLE
The typo of Tokyo TG location in region mapping list

### LINKED ISSUE #2005: Fix typo of tokyo TG location in region mapping list
/kind bug
/area provider/ibmcloud

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

TG location for tokyo is mentioned as jp-rok instead of jp-tok.

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version:
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by aman4433**
**What this PR does / why we need it**: This PR addresses a typo in the region mapping list for the Tokyo TG location. The Tokyo location was previously listed as jp-rok instead of the correct jp-tok. This fix ensures that the Tokyo TG location is correctly identified as jp-tok.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #2005 

**Special notes for your reviewer**:

/area provider/ibmcloud

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by Karthik-K-N — COMMENTED** [review]
/lgtm

**Review by mkumatag — APPROVED** [review]
/lgtm

**Pull request merged**
