### PR TITLE
User klog.Background() instead of textlogger

### PR DESCRIPTION
**Pull request by Karthik-K-N**
**What this PR does / why we need it**:

Currently we are using textlogger, using which we are not able to see any V level logs, For example. log.V(3).Info("hello").
This PR contains the change which uses klog.Background() instead of text logger.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

/area provider/ibmcloud

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Release note**:

```release-note
Switch to kloger instead of textloger
```

### CODE REVIEW

**Review by mkumatag — APPROVED** [review]
/lgtm

**Comment by mkumatag** [comment]
@Karthik-K-N fix the CI

**Review by Amulyam24 — COMMENTED** [review]
/lgtm

**Pull request merged**
