### PR TITLE
fix issue #286

### LINKED ISSUE #286: gernate-yaml seems broke
/kind bug
/area provider/ibmcloud

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
```
 $ ./generate-yaml.sh ./clouds.yaml ubuntu
no output folder provided, use name 'out' by default
cp: cannot stat '/home/posix4e/cluster-api-provider-ibmcloud/cmd/clusterctl/examples/ibmcloud/provider-component/clouds-secrets/configs/../../../../../../../vendor/sigs.k8s.io/cluster-api/config': No such file or directory
```

**What did you expect to happen:**
```
$ ./generate-yaml.sh ./clouds.yaml ubuntu
no output folder provided, use name 'out' by default
```

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
Fixed it by going back to 66ae8f6f77291c7753d9ab8c0d4361612547eaf0

**Environment:** Linux

### PR DESCRIPTION
**Pull request by songleo**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #286 

**Specify your PR reviewers**:

/cc @gyliu513 @jichenjc @xunpan

**Special notes for your reviewer**:

/area provider/ibmcloud

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by xunpan** [comment]
Please download `/config` on demands and use `curl` instead of `wget`.
Please add related directory in `.gitigore` to avoid git maintainance for useless files.

**Comment by songleo** [comment]
I have add related directory to `.gitigore` and use `curl` instead of `wget`.

**Comment by xunpan** [comment]
Thanks for your updated.
It is preferred to have below 2 changes:
1. squash `curl` commit.
   It only fix a issue introduced in previous commit in this ticket. It makes less sense in commit history management.
2. extract only the necessary files into target directory directly instead of extracting all and copying sub directory.

**Comment by songleo** [comment]
Thanks for your comments, I will update and resubmit.

**Pull request merged**
