### PR TITLE
Update cluster-api to v1.9.x

### LINKED ISSUE #2056: CAPI v1.9.0-beta.0 has been released and is ready for testing
CAPI v1.9.0-beta.0 has been released and is ready for testing.
Looking forward to your feedback before v1.9.0 release!

## For quick reference

- [CAPI v1.9.0-beta.0 release notes](https://github.com/kubernetes-sigs/cluster-api/releases/tag/v1.9.0-beta.0)
- [Shortcut to CAPI git issues](https://github.com/kubernetes-sigs/cluster-api/issues)

## Following are the planned dates for the upcoming releases

CAPI v1.9.0 will be released on **Wednesday, 6th November 2024**.

More details of the upcoming schedule can be seen at [CAPI v1.9.0 release timeline](https://github.com/kubernetes-sigs/cluster-api/tree/main/docs/release/releases/release-1.9.md#timeline).

### PR DESCRIPTION
**Pull request by Amulyam24**
**What this PR does / why we need it**:
Update cluster-api to v1.9.x, the following changes are made
1. Update k8s to 1.31
2. `sigs.k8s.io/cluster-api/errors` is deprecated, move away from it
3. While setting up the controllers, functions returning predicates accept an additional argument
4. Replaced the deprecated `ClusterUnpausedAndInfrastructureReady` with `ClusterPausedTransitionsOrInfrastructureReady`, ref - https://github.com/kubernetes-sigs/cluster-api/pull/11300

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #2056 

**Special notes for your reviewer**:

/area provider/ibmcloud

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Release note**:

```release-note
Update cluster-api to v1.9.x
```

### CODE REVIEW

**Comment by mkumatag** [comment]
@Amulyam24 can you mention all the changes made with more information

**Comment by Amulyam24** [comment]
/unhold

PR is ready for review @Prajyot-Parab @mkumatag

**Review by mkumatag — APPROVED** [review]
/lgtm

**Pull request merged**
