### PR TITLE
Update cluster-api to v1.7.0-beta.0

### LINKED ISSUE #1660: CAPI v1.7.0-beta.0 has been released and is ready for testing
CAPI v1.7.0-beta.0 has been released and is ready for testing.
Looking forward to your feedback before v1.7.0 release!

## For quick reference

- [CAPI v1.7.0-beta.0 release notes](https://github.com/kubernetes-sigs/cluster-api/releases/tag/v1.7.0-beta.0)
- [Shortcut to CAPI git issues](https://github.com/kubernetes-sigs/cluster-api/issues)

## Following are the planned dates for the upcoming releases

CAPI v1.7.0 will be released on **Tuesday, 16th April 2024**.

More details of the upcoming schedule can be seen at [CAPI v1.7.0 release timeline](https://github.com/kubernetes-sigs/cluster-api/tree/main/docs/release/releases/release-1.7.md#timeline).

### PR DESCRIPTION
**Pull request by Amulyam24**
**What this PR does / why we need it**:
Updates
- cluster-api to v1.7.0-beta.0
- k8s to 1.29

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1660 

**Special notes for your reviewer**:

/area provider/ibmcloud

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Release note**:

```release-note
Update cluster-api to v1.7.0-beta.0
```

### CODE REVIEW

**Comment by Amulyam24** [comment]
/hold 
To-do: Test cluster creation and update

**Comment by mkumatag** [comment]
Please update the [metadata.yaml](https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/blob/main/metadata.yaml) as well with the new entry.

**Comment by Amulyam24** [comment]
Testing completed with a successful run, PR is ready for review
/unhold

**Review by mkumatag — APPROVED** [review]
/lgtm

**Pull request merged**
