### PR TITLE
convert Ibmcloud to IBMCloud for better UX

### PR DESCRIPTION
**Pull request by chenzhiwei**
**What this PR does / why we need it**:

convert Ibmcloud to IBMCloud for better UX

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes # https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/issues/193

**Specify your PR reviewers**:

/cc @gyliu513 @jichenjc @xunpan

**Special notes for your reviewer**:

/sig ibmcloud

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by gyliu513** [comment]
LGTM

Leave to @xunpan @jichenjc for approve.

**Comment by jichenjc** [comment]
I am ok with change, but I want to make sure we did some test on this already ? as fix typo usually need some effort ...

**Comment by chenzhiwei** [comment]
The change was made by batch command, so there should be no issue unless it already has typo.

I did not get a chance to run an e2e test yet, but I think it should ok.

**Comment by xunpan** [comment]
Thanks for your PR.

/lgtm

**Pull request merged**
