### PR TITLE
Bump actions version

### PR DESCRIPTION
**Pull request by Prajyot-Parab**
**What this PR does / why we need it**:
- Bump actions version
ref- https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

/area provider/ibmcloud

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Release note**:

```release-note
Bump actions version
```

### CODE REVIEW

**Review by Amulyam24 — COMMENTED** [review]
Should we also bump `actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # tag=v4.1.1` to keep the workflow updated?

**Comment by Prajyot-Parab** [comment]
> Should we also bump `actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # tag=v4.1.1` to keep the workflow updated?

CAPI is using same as of now so stickting to same version.

> Should we also bump `actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # tag=v4.1.1` to keep the workflow updated?

Fixed it, done.

**Review by Amulyam24 — APPROVED** [review]
/lgtm

**Review by mkumatag — APPROVED** [review]
/lgtm

**Pull request merged**
