### PR TITLE
fix lint/boilerplate issues

### PR DESCRIPTION
**Pull request by Prajyot-Parab**
Signed-off-by: Prajyot-Parab <prajyot.parab2@ibm.com>

**What this PR does / why we need it**:
- Fix lint/boilerplate issues

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

/area provider/ibmcloud

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Release note**:

```release-note
Fix lint failures
```

### CODE REVIEW

**Comment by mkumatag** [comment]
I think this error happening with golang 1.19 version, check your golang version.. this project still uses 1.18

**Comment by Prajyot-Parab** [comment]
> I think this error happening with golang 1.19 version, check your golang version.. this project still uses 1.18

Okay, yes my editor updated my golang

**Comment by Prajyot-Parab** [comment]
Issue seen with go1.18 as well (reopening PR) @Karthik-K-N I guess this is the same issue you were facing last time.

**Comment by mkumatag** [comment]
I don't see any harm fixing this one, lets reopen and merge! oops, I see branch is already deleted!

lemme submit a different PR to fix this one.

**Pull request closed without merging**
