### PR TITLE
Added sig ibmcloud to issues and pr template.

### PR DESCRIPTION
**Pull request by gyliu513**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Release note**:

```release-note
NONE
```

/cc @xunpan @jichenjc

### CODE REVIEW

**Comment by xunpan** [comment]
@gyliu513  what is the purpose to set this label?

**Comment by gyliu513** [comment]
@xunpan this label can help us to get issues and prs for ibmcloud with ease.

**Comment by spzala** [comment]
> @xunpan this label can help us to get issues and prs for ibmcloud with ease.

Agree!

**Pull request merged**
