### PR TITLE
started the support for cluster class vpc

### LINKED ISSUE #974: Add ClusterClass support for VPC
/kind feature
/area provider/ibmcloud

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
ClusterClass support for Power VS was added as a part of https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/pull/967, Similar approach can be taken for VPC

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

### PR DESCRIPTION
**Pull request by swastik959**
**What this PR does / why we need it**: cluster class support for vpc

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #974

**Special notes for your reviewer**:

/area provider/ibmcloud

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by mkumatag** [comment]
@swastik959 wondering if you can fix the CI issues to proceed further with the review process.

**Comment by kishen-v** [comment]
Supported through - https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/pull/1500.

**Comment by kishen-v** [comment]
Hi @Karthik-K-N, @Prajyot-Parab. 
This PR may be closed as #1500 has been merged.

**Pull request closed without merging**
