### PR TITLE
Changes related to sig ibm cloud rename

### PR DESCRIPTION
**Pull request by spzala**
**What this PR does / why we need it**:
Changes related to sig ibm cloud became provider ibm cloud. 

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes # 269

**Specify your PR reviewers**:

/cc @gyliu513 @jichenjc @xunpan

**Special notes for your reviewer**:

/area provider/ibmcloud

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by jichenjc** [comment]
seems the owner files are invalid...

**Comment by gyliu513** [comment]
@spzala do you want to update this file https://github.com/kubernetes/community/blob/master/sig-cloud-provider/OWNERS ?

**Comment by spzala** [comment]
> @spzala do you want to update this file https://github.com/kubernetes/community/blob/master/sig-cloud-provider/OWNERS ?

@gyliu513 I guess we shouldn't update it. The owners there are sig leads - so 3 current leads. It doesn't include the sub-project leads. Also, I believe that should not have anything to do with the plug-in invalid-owners-file error we are seeing here. The error is because Ajay and Khalid and possibly Richard are not org member. 

The sub-project owners are listed here, https://github.com/kubernetes/community/blob/master/OWNERS_ALIASES#L182
And you can see a commit below related to removing non-org member, 
https://github.com/kubernetes/community/pull/3941/commits/fd0631e420901228f1ff8a5ee70a595f55abe4bd  (Neither are kubernetes org members) 

I guess what we can do is - either remove non-org member owners from the owners file and add them later once they become member or work with them and see if they can apply for membership now and wait for them to become member. I will talk to Khalid and Richard. Does that sounds good? Thanks!

**Comment by gyliu513** [comment]
@spzala Yes, we can remove non kubernetes org member first ;-)

**Pull request merged**
