### PR TITLE
Update golang version to 1.21.12

### PR DESCRIPTION
**Pull request by Amulyam24**
**What this PR does / why we need it**:
Update golang version to 1.21.12 to fix trivy vulnerabilities

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

/area provider/ibmcloud

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Release note**:

```release-note
Update golang version to 1.21.12
```

### CODE REVIEW

**Comment by Amulyam24** [comment]
This PR needs to be cherry-picked to release-0.8 and release-0.7

**Review by Prajyot-Parab — APPROVED** [review]
/lgtm

**Pull request merged**
