### PR TITLE
Update docker to 1.18 version

### LINKED ISSUE #666: Adopt k8s 1.24
/kind feature
/area provider/ibmcloud

**Describe the solution you'd like**

- [ ] Golang
- [ ] cluster-api update
- [ ] k8s update in the go.mod
- [ ] k8s version update in the prow job

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

### PR DESCRIPTION
**Pull request by mkumatag**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #666 

**Special notes for your reviewer**:

/area provider/ibmcloud

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by mkumatag** [comment]
Waiting for https://github.com/kubernetes/test-infra/pull/26678 to merge

**Review by Prajyot-Parab — APPROVED** [review]
/lgtm

**Comment by mkumatag** [comment]
/unhold

Now all the jobs are run with 1.24 version

**Pull request merged**
