### PR TITLE
Add unit tests for webhooks

### PR DESCRIPTION
**Pull request by Amulyam24**
**What this PR does / why we need it**:
Adds UT for webhooks

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

/area provider/ibmcloud

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Release note**:

```release-note

```

### CODE REVIEW

**Review by mkumatag — CHANGES_REQUESTED** [review]
Instead of calling the ValidateCreate/ValidateUpdate directly, wondering if we can call the flow via testenv like aws provider is doing it here - https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/main/api/v1beta1/awsmachine_webhook_test.go

**Comment by Amulyam24** [comment]
@mkumatag, made the changes, PTAL.

**Review by mkumatag — APPROVED** [review]
/lgtm

**Pull request merged**
