### PR TITLE
Add redirect url for meeting document

### PR DESCRIPTION
**Pull request by Karthik-K-N**
**What this PR does / why we need it**:

This would beautify the meeting notes link. Like below
1. Existing way: https://docs.google.com/document/d/1oWnqXy1VFv0E3kovQoZfS6IlVP0L4eaQsN-2HYC_6_A
2. New way:  https://cluster-api-ibmcloud.sigs.k8s.io/agenda.html

Reference: https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/2125/files

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

/area provider/ibmcloud

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Release note**:

```release-note
None
```

### CODE REVIEW

**Review by Amulyam24 — COMMENTED** [review]
@Karthik-K-N, how can I view this change? Will it be part of the book?

**Comment by mkumatag** [comment]
> @Karthik-K-N, how can I view this change? Will it be part of the book?

https://deploy-preview-1986--kubernetes-sigs-cluster-api-ibmcloud.netlify.app/agenda.html

**Comment by Amulyam24** [comment]
> > @Karthik-K-N, how can I view this change? Will it be part of the book?
> 
> https://deploy-preview-1986--kubernetes-sigs-cluster-api-ibmcloud.netlify.app/agenda.html

Thanks @mkumatag! 
/lgtm

**Review by Prajyot-Parab — APPROVED** [review]
/lgtm

**Comment by Karthik-K-N** [comment]
I think currently https://cluster-api-ibmcloud.sigs.k8s.io/ is pointing to release-0.7 branch is this correct? 
If so can I cherry-pick this PR to 0.8 and 0.7 respectively so https://cluster-api-ibmcloud.sigs.k8s.io/agenda.html works?

Because https://main.cluster-api-ibmcloud.sigs.k8s.io/agenda.html is working as expected.

**Comment by Amulyam24** [comment]
> I think currently https://cluster-api-ibmcloud.sigs.k8s.io/ is pointing to release-0.7 branch is this correct?

It will be pointing to release-0.8 branch

>  If so can I cherry-pick this PR to 0.8 and 0.7 respectively so https://cluster-api-ibmcloud.sigs.k8s.io/agenda.html works?
> 
> Because https://main.cluster-api-ibmcloud.sigs.k8s.io/agenda.html is working as expected.

yes

**Pull request merged**
