### PR TITLE
Update cluster-api/hack/tools

### LINKED ISSUE #531: Update hack/tools/go.mod for the capi tools
/kind bug
/area provider/ibmcloud

**What steps did you take and what happened:**
Update the hack/tools/go.mod with the 1.1.0 capi tools

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version:
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by Amulyam24**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #531 

**Special notes for your reviewer**:

/area provider/ibmcloud

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by Amulyam24** [comment]
cc @mkumatag

**Comment by Amulyam24** [comment]
The failure on `make verify` could be rectified by replacing it with the correct version for cluster-api
```
replace (
	sigs.k8s.io/cluster-api => sigs.k8s.io/cluster-api v1.1.0
	sigs.k8s.io/cluster-api/test => sigs.k8s.io/cluster-api/test v1.1.0
)
```
after the above change, seeing this now
```
cd hack/tools; go mod tidy
sigs.k8s.io/cluster-api-provider-ibmcloud/hack/tools imports
        github.com/itchyny/gojq/cmd/gojq imports
        github.com/itchyny/gojq/cli imports
        github.com/mattn/go-runewidth loaded from github.com/mattn/go-runewidth@v0.0.9,
        but go 1.16 would select v0.0.13
sigs.k8s.io/cluster-api-provider-ibmcloud/hack/tools imports
        sigs.k8s.io/controller-runtime/tools/setup-envtest imports
        go.uber.org/zap tested by
        go.uber.org/zap.test imports
        go.uber.org/goleak loaded from go.uber.org/goleak@v1.1.11-0.20210813005559-691160354723,
        but go 1.16 would select v1.1.12
sigs.k8s.io/cluster-api-provider-ibmcloud/hack/tools imports
        github.com/golangci/golangci-lint/cmd/golangci-lint imports
        github.com/golangci/golangci-lint/pkg/commands imports
        github.com/gofrs/flock tested by
        github.com/gofrs/flock.test imports
        gopkg.in/check.v1 loaded from gopkg.in/check.v1@v1.0.0-20200227125254-8fa46927fb4f,
        but go 1.16 would select v1.0.0-20201130134442-10cb98267c6c
sigs.k8s.io/cluster-api-provider-ibmcloud/hack/tools imports
        sigs.k8s.io/controller-runtime/tools/setup-envtest imports
        go.uber.org/zap tested by
        go.uber.org/zap.test imports
        go.uber.org/goleak imports
        go.uber.org/goleak/internal/stack loaded from go.uber.org/goleak@v1.1.11-0.20210813005559-691160354723,
        but go 1.16 would select v1.1.12
```
@mkumatag, looks like something is getting mixed up here, any idea?

**Comment by mkumatag** [comment]
> @mkumatag, looks like something is getting mixed up here, any idea?

I tried following steps and I could able to build the doc with recent updates to the hack/tool go.mod update.

```shell
$ cd hack/tools
# commit sha for the v1.1.0 release
$ go get sigs.k8s.io/cluster-api/hack/tools@e2aafb60cdf72ea086b56727dfac76f13ac6f9fe
$ cd ../..
$ make -C docs/book build
make -C ../../hack/tools bin/mdbook
curl -sL -o share/mdbook.tar.gz "https://github.com/rust-lang/mdBook/releases/download/v0.4.5/mdBook-v0.4.5-x86_64-apple-darwin.tar.gz"
tar xfvz share/mdbook.tar.gz -C bin
tar: Failed to set default locale
x mdbook
chmod +x bin/mdbook
touch -m bin/mdbook
make -C ../../hack/tools bin/mdbook-embed
go build -tags=tools -o bin/mdbook-embed sigs.k8s.io/cluster-api/hack/tools/mdbook/embed
go: downloading sigs.k8s.io/kubebuilder/docs/book/utils v0.0.0-20211028165026-57688c578b5d
make -C ../../hack/tools bin/mdbook-releaselink
go build -tags=tools -o bin/mdbook-releaselink sigs.k8s.io/cluster-api/hack/tools/mdbook/releaselink
make -C ../../hack/tools bin/mdbook-tabulate
go build -tags=tools -o bin/mdbook-tabulate sigs.k8s.io/cluster-api/hack/tools/mdbook/tabulate
../../hack/tools/bin/mdbook build
2022-02-07 20:22:27 [INFO] (mdbook::book): Book building has started
2022-02-07 20:22:31 [INFO] (mdbook::book): Running the html backend

**Review by mkumatag — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
