### PR TITLE
fix warning '7c592eb' should not be abbreviated form

### LINKED ISSUE #247: dep: WARNING: revision "7c592eb" should not be in abbreviated form
/kind bug
/sig ibmcloud

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
dep ensure
dep: WARNING: revision "7c592eb" should not be in abbreviated form

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version:
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by jichenjc**
also, updated to latest commit as some API already not supported
we should not use old stuff

see https://github.com/softlayer/softlayer-go/commit/ba6e7f29521771a05a8faa6c1782735b4b74dc36
for more info

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #247 

**Specify your PR reviewers**:

/cc @gyliu513 @jichenjc @xunpan

**Special notes for your reviewer**:

/sig ibmcloud

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by xunpan** [comment]
@clyang82 @jichenjc 
I'd like to know if this is related to `dep` version or we lost something when we changed to the revision?

**Comment by clyang82** [comment]
> @clyang82 @jichenjc
> I'd like to know if this is related to `dep` version or we lost something when we changed to the revision?

I do not think this is related with `dep` version. the proposal is to use a stable revision for our repo since there is no release for `softlayer-go`

**Comment by jichenjc** [comment]
it's not related to dep version, instead, we used a abbreviated commit number leads to warning
use a full number remove the problem

and I found there's a big change recently to remove unsupported stuffs as well, so we can include that

**Comment by xunpan** [comment]
got it. 

/lgtm

**Pull request merged**
