### PR TITLE
Remove unwanted logs

### PR DESCRIPTION
**Pull request by mkumatag**
**What this PR does / why we need it**:

The removed log messages weren't much useful but increases the logfile size, hence removed them.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

/area provider/ibmcloud

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by Prajyot-Parab** [comment]
@mkumatag linter throwing error resulting test flow failure.

**Comment by mkumatag** [comment]
> @mkumatag linter throwing error resulting test flow failure.

CI is happy now :)

**Review by Prajyot-Parab — APPROVED** [review]
/lgtm

**Pull request merged**
