### PR TITLE
Bump capibm images to k8s 1.28.x for e2e flow

### PR DESCRIPTION
**Pull request by Prajyot-Parab**
**What this PR does / why we need it**:
- Bump capibm images to k8s 1.28.x for e2e flow

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

/area provider/ibmcloud

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Release note**:

```release-note
Bump capibm images to k8s 1.28.x for e2e flow
```

### CODE REVIEW

**Review by Amulyam24 — APPROVED** [review]
/lgtm

@Prajyot-Parab, hope the images are imported to the VPC and PowerVs regions for E2E.

**Comment by mkumatag** [comment]
> /lgtm
> 
> @Prajyot-Parab, hope the images are imported to the VPC and PowerVs regions for E2E.

@Prajyot-Parab can you confirm if the backend service instances are all imported with the images so that we can merge this PR?

**Comment by Prajyot-Parab** [comment]
> /lgtm
> 
> @Prajyot-Parab, hope the images are imported to the VPC and PowerVs regions for E2E.

Yes done already

**Comment by Prajyot-Parab** [comment]
> > /lgtm
> > @Prajyot-Parab, hope the images are imported to the VPC and PowerVs regions for E2E.
> 
> @Prajyot-Parab can you confirm if the backend service instances are all imported with the images so that we can merge this PR?

Yes already imported.

**Review by mkumatag — APPROVED** [review]

**Pull request merged**
