### PR TITLE
Add waiter functions for control-plane

### PR DESCRIPTION
**Pull request by Prajyot-Parab**
**What this PR does / why we need it**:
- Add waiter functions for control-plane

This function is introduced to give additional breather for e2e flow to avoid failure due to timeout issue while applying CNI.

Note - we shall observe the future CI runs to learn its impact.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

/area provider/ibmcloud

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Release note**:

```release-note
Add waiter functions for control-plane
```

### CODE REVIEW

**Review by Amulyam24 — APPROVED** [review]
/lgtm

**Review by mkumatag — APPROVED** [review]
/lgtm

**Pull request merged**
