### PR TITLE
Refactor unit test framework

### PR DESCRIPTION
**Pull request by Amulyam24**
**What this PR does / why we need it**:
Refactors the unit tests to create the test environment using envtest and not use a fake client.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

/area provider/ibmcloud

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by mkumatag** [comment]
@Prajyot-Parab ptal

**Comment by Amulyam24** [comment]
> @Amulyam24 I don't see newly added tests in the report here - https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-ibmcloud/705/pull-cluster-api-provider-ibmcloud-test/1536992422322507776, can you please help me understand where to find the results?

@mkumatag, the new tests added under controller aren't being reported in junit format due to which we can't see their result in the log. I'll add the change in a follow-up PR to this to fix it.

**Review by mkumatag — APPROVED** [review]
Tests are running but aren't exposed via junit format, will explore this in a different work item.

**Pull request merged**
