### PR TITLE
Refactor PowerVSClusterscope function to faciliate UT integration

### PR DESCRIPTION
**Pull request by Karthik-K-N**
**What this PR does / why we need it**:

1. This PR refactors the code to make use of factory functions which can be used during unit test cases for easy overriding of the function.
2. Changes are made to PowerVSClient to reuse the session or authenticator if already present in the options passed
3. Added some sample UT to demonstrate the usage of factory functions 

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

/area provider/ibmcloud

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Release note**:

```release-note
Refactor PowerVSClusterscope function to faciliate UT integration
```

### CODE REVIEW

**Comment by Karthik-K-N** [comment]
/hold

testing pending.

**Comment by Karthik-K-N** [comment]
@mkumatag @Amulyam24 @dharaneeshvrd Please take a look at the approach and let me know your opinion. If you think of any better approach dont forget to comment here.

**Review by Amulyam24 — COMMENTED** [review]
Thanks @Karthik-K-N, overall LGTM!

**Comment by Karthik-K-N** [comment]
I have verified the workflow with cluster creation and able to see cluster getting created successfully.

```
karthikkn@Karthiks-MacBook-Pro templates % oc get ibmpowervsmachines
NAME                                         CLUSTER                  AGE     READY   STATE    HEALTH
karthikkn-capi-powervs-control-plane-8mt9p   karthikkn-capi-powervs   30m     true    ACTIVE   OK
karthikkn-capi-powervs-control-plane-hjpzj   karthikkn-capi-powervs   16m     true    ACTIVE   OK
karthikkn-capi-powervs-control-plane-k55d2   karthikkn-capi-powervs   8m36s   true    ACTIVE   WARNING
karthikkn-capi-powervs-md-0-tmx5r-84rnw      karthikkn-capi-powervs   50m     true    ACTIVE   WARNING
```

**Comment by Karthik-K-N** [comment]
@dharaneeshvrd @mkumatag Please review this PR when you get some time, This will unblock in adding unit test cases.

**Comment by dharaneeshvrd** [comment]
Changes looks good to me as well!

**Review by mkumatag — APPROVED** [review]
/lgtm

**Pull request merged**
