### PR TITLE
Bump golang from 1.20.10 to 1.20.11

### PR DESCRIPTION
**Pull request by Amulyam24**
**What this PR does / why we need it**:
Bump golang from 1.20.10 to 1.20.11

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

/area provider/ibmcloud

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Release note**:

```release-note
Bump golang from 1.20.10 to 1.20.11
```

### CODE REVIEW

**Review by Prajyot-Parab — CHANGES_REQUESTED** [review]
@Amulyam24 
Need to update here as well -https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/blob/1e75b4119fd8591aa3540e6c262335d1f05cf997/Makefile#L21

If you can pass go version from one place to everywhere it is being referred as part of this PR that would be helpful. (then we have to update only a single line going forward)

**Review by mkumatag — APPROVED** [review]
/lgtm

**Comment by mkumatag** [comment]
Lets find a way to tackle this, otherwise will end up having all possible different versions everywhere!
>If you can pass go version from one place to everywhere it is being referred as part of this PR that would be helpful. (then we have to update only a single line going forward)

**Comment by mkumatag** [comment]
@Amulyam24 can you manually update that location as well and merge this PR? lets create a separate task to add a check

**Review by mkumatag — CHANGES_REQUESTED** [review]
Two questions:
1. What will happen if someone trigger the `docker build` outside of Makefile
2. Will Dependabot updates the docker version when there is a new version available?

**Review by mkumatag — APPROVED** [review]
/lgtm
/unhold

**Pull request merged**
